volumes:
  caddy_data:
  caddy_config:

services:
  caddy:
    image: pomodoro-timer-web-react:dev
    restart: unless-stopped
    ports:
      - "8082:80"
      # - "8083:443"
      # - "8083:443/udp"
    volumes:
      - ./conf:/etc/caddy
      - caddy_data:/data
      - caddy_config:/config

  backend:
    image: pomodoro-timer-backend-dotnet:dev
    restart: unless-stopped
    environment:
      - CONNECTION_STRING=Data Source=/data/pomodoro-timer.db
      - HANGFIRE_CONNECTION_STRING=/data/hangfire.db
    volumes:
      - /opt/my/pomodoro-timer/data:/data
    ports:
      - 8081:8080